; Strings Internationalization File - English
; This file contains all UI strings used in IntraWeb applications

[Strings]
Ok=Ok
PermissionDenied=Permission denied
ShowMessageNotSupported=ShowMessage not supported
SecureModeRequired=Secure mode is required for this form.
NonSecureModeRequired=Non-Secure mode is required for this form.
NotSupportedDuringPartialUpdate=That change is not supported during partial update.
WebApplicationRequiered=WebApplication is requiered in order to use this function.
TerminateAndRedirectMsg=Please wait a moment.
OptionsMenuCaption=&Options
DeviceSimulationMenuCaption=&Device Simulation
HTML32Caption=HTML 3.2
WMLCaption=WML
XHTMLMPCaption=XHTML MP
PleaseWait=Please wait...
HTML32Hint=Override browser type and use HTML 3.2 mode.
WMLHint=Override browser type and use WML mode.
XHTMLMPHint=Override browser type and use XHTML MP mode
UnknownClientType=Unknown client type.
CannotShowNonAppForms=Cannot show non-app forms.
CannotHideNonAppForms=Cannot hide non-app forms.
CannotReleaseNonAppForms=Cannot release non-app forms.
UnknownBrowserType=Your browser is not supported. User Agent string: %s
UnidentifiedBrowserType=Your browser is not supported.
MustBeAppForm=Form must be an application form.
WrongIPFoession=The IP you are using is different than the one that initiated the session.
WrongBrowserFoession=The browser you are using is different than the one that initiated the session.
InvalidFormId=Invalid page context
ValidationRequeredField=%s is a required field.
SelectionRequired=A value must be selected for %s.
InvalidComponentName="%s" is not a valid component name.
DroppedConnection=Client Dropped Connection
NotFound=%s not found.
PopupBlocked=Popup is blocked. Please disable popup blocker to continue.
NoSubmitComponent=Cannot find submit component.
NoSubmitHandler=Submit control (%s) does not have a handler.
InvalidFunction=This function is not valid for this server type.
InvalidHeight="%s" is not a valid height.
InvalidWidth="%s" is not a valid width.
IndexOutOfBounds=Index out of bounds.
NoServerController=No server controller has been created.
SessionAlreadyLocked=Session is already locked.
NotForThisProcess=The session does not belong to this process.
RefreshWarning=You have attempted to post or refresh data from a page that depends on information that is no longer available to the server application. Your attempted changes will be ignored. You will now be resynced to the current place  in the application.
ResourceNotFound=Resource %s not found.
NoMainForm=No main form is defined.
DeviceNotSupported=Device not supported
NoServerControllerClass=No server controller is defined.
UnknownSessionMethod=Unknown session tracking method
InvalidBrowser=Your browser was detected as %s, identifying itself as %s. One of the following browsers is required:  
MessageDialog=Message Dialog
ColorRed=red
ColorBlue=blue
ColorGreen=green
ColorYellow=yellow
ColorBrown=brown
TextError=Error: 
CannotReceiveFocus=Control cannot receive focus
ErrorCreatingSession=Error creating session
IWSessionTerminated=This session has been terminated
UnknownBrowser=Unknown or Unrecognized
IE=Internet Explorer
NS6Gecko=Netscape 6 (Gecko)
NS7Gecko=Gecko engine (Netscape, FireFox, etc)
Opera=Opera
Chrome=Chrome
NS4=Netscape 4
Other=Other
HTML32Test=HTML 32 Test
WMLTest=WML Test
WAP=Generic WAP Browser
XHTMLMPTest=XHTML MP Test
Safari=Safari
Unrecognizable=Unknown browser type.
NoCookieSupport=Cookies are disabled in your browser. Please enable cookie support and try to restart the application.
CantFindInternalFile=Cannot find internal file: %s
ExecuteError=Error while launching browser: %s.
IWVeion=IntraWeb Veion: %s
LicenseNumber=License Number: %s
btnNameFit=Fit
btnNamePrior=Prior
btnNameNext=Next
btnNameLast=Last
btnNameInsert=Insert
btnNameDelete=Delete
btnNameEdit=Edit
btnNamePost=Post
btnNameCancel=Cancel
btnNameRefresh=Refresh
UnsupportedFieldType=Unsupported field type in DBLink
NoRefereshWhileInEdit=Cannot refresh grid while data is in edit or insert mode.
InvalidResponse=%s is not a valid response.
DeleteMessage=Are you sure you want to delete this record?
UpdateMessage=Are you sure you want to update this record?
CancelMessage=Are you sure you want to cancel your changes to this record?
DataSetNotEditing= Set %s.AutoEdit property to TRUE, or manually set %s to Edit or Insert mode before updating records.
InvalidSessionTimeout=Invalid session timeout value.
EmptyWorkAreaPath=Work Area Path not set.
FormPreviewError=Error loading Form Preview Manager. Check to see if it is installed.
HTMLEditorError=Error loading HTML Layout Manager. Check to see if it is installed.
IE55OrLater=Internet Explorer 5.5 or higher is required to run the editor
ScriptEditorCaption=IntraWeb Event Scripts Editor
ScriptEditorEvent=Event
ScriptEditorCode=Code
OKButton=OK
CancelButton=Cancel
ApplyButton=&Apply
NewRoot=New &Root Item
NewItem=&New Item
DeleteItem=&Delete Item
EditCaption=&Edit Caption
MsgDeleteItem=Delete "%s"?
ApacheDSOError=Apache DSOs must be a library.
ISAPIError=ISAPI veion must be a library.
StandaloneError=Standalone must be .exe
ToolBarError=Error loading toolbar button images.
Redirecting=Redirecting...
CanUseIWControlOnVCLForm=IntraWeb controls are not valid on non IntraWeb forms.
No4On32Form=Only 3.2 controls should be placed on a 3.2 Form
No32On4Form=Only 4.0 controls should be placed on a 4.0 Form
DublicateEventHandler=This event handler already has code associated to it
MetaFileNotSupported=MetaFile not supported
LoadImageError=Could not load image
UnrecognizedCommand=Unrecognized Command: 
LayoutMgrNeeded32=For HTML 3.2 a layout manager is required. Make sure that you have one associated to the form and this its Able property is set to True
LogExecute=Execute: 
LogCacheFile=Cache File: 
LogInternalGraphic=Internal Graphic: 
LogJavaScript=Javascript: 
LogNewSession=New session: 
LogExternalFile=External File: 
LogExplicitStop=Explicit Stop: 
LogUnrecognizedCommand=Unrecognized Command: 
LogActiveSessions=Active Sessions: 
LogResizeCommand=Resize: 
LogUpdateCommand=Partial Update: 
CleaessionsCaption=C&lear Sessions
CleaessionsHint=Clear all active sessions.
CopyClipboardCaption=&Copy URL to Clipboard
CopyClipboardHint=Copies the starting URL for the application to the clipboard.
ShowDebugInfoCaption=&Show Debug Information
ShowDebugInfoHint=Shows detailed debug information in the log window.
ExitCaption=E&xit
ExitHint=Stop the service and exit the application.
ExecuteCaption=E&xecute
ExecuteHint=Launch selected browser and execute application.
ExecuteDefaultCaption=Execute via &Default browser
ExecuteDefaultHint=Launch default browser and execute application.
ExecuteIECaption=Execute via &IE
ExecuteIEHint=Launch Internet Explorer and execute application.
ExecuteMozillaCaption=Execute via &Mozilla
ExecuteMozillaHint=Launch Mozilla and execute application.
ExecuteFirefoxCaption=Execute via &Firefox
ExecuteFirefoxHint=Launch Firefox and execute application.
ExecuteNS6Caption=Execute via &Netscape
ExecuteNS6Hint=Launch Netscape and execute application.
ExecuteOperaCaption=Execute via &Opera
ExecuteOperaHint=Launch Opera and execute application.
UseSSLCaption=Use SS&L
UseSSLHint=Use SS&L
ParamCaption=&Parameters
ParamHint=Set parameters for application.
AboutCaption=&About
AboutHint=Display about box.
FileMenuCaption=&File
RunMenuCaption=&Run
SelectBrowserCaption=Select browser
HelpCaption=&Help
ToolBarCaption=Toolbar
UseParamQueryTitle=URL Parameters
UseParamQueryPrompt=Enter parameters for URL:
ConnectionSpeedCaption=Set Simulated Connection speed
IncorrectSpeed=Incorrect connection speed value (%s).
SimulSpeed=Simulated Connection speed
ConnectionSpeed=Connection Speed: 
CanSetControlToSelf=You cannot assign the control to itself
ZLibNotFound=zlib.dll not found in %s
WrongZLibVer=Wrong ZLib veion
Today=Today
Previous=Previous
Next=Next
EditHTML=Edit
PreviewHTML=Preview
InvalidTimeEditFormat=The value of %s is in an incorrect format. lease correct the value.
MissingContainerOnFrame=Frame container not found.
LogCSSRequest=CSS:
ExceptionSessionExpiredMsg=Your session has expired due to inactivity.
ExceptionSessionInvalidMsg=Session ID is invalid.
ExceptionSessionExpired=Your session has expired. You will have to restart the application. In order to keep sessions from   expiring you may set the session timeout parameter to a higher value. The current session timeout value is %d minute%s.
ExceptionSecurityCheck=Security check failed. Please restart the application.
ExceptionOther=Depending on the error condition, it might be possible to restart the application.
TrappedException=The following exception%s occured#13#10%s
ExceptionDetailsHidden=[Error details are disabled in server configuration]
Doodle=This edition is limited to 5 concurrent active sessions
BackButtonMessage=Back button cannot be used in this page
AuthFailedMessage=Authentication failed
CookieCheckMessage=This application requires cookies to be enabled. Please enable cookies in your browsers settings, close your current web session and try again.
ScriptRecorder=Script Recorder
Browser=Browser
Tools=Tools
Settings=Settings
View=View
MenuSaveSettings=Save Settings
Restore=Restore
Shutdown=Shutdown
RunMinimized=Run Minimized
RunInTrayIcon=Run in Tray icon
SmallIcons=Small Icons
LargeIcons=Large Icons
DebugLog=Debug Log
UseSSL=Use SSL
Default=Default
Execute=Execute
CopyStartURL=Copy Start URL
ResetSessions=Reset Sessions
ResetSentData=Reset Sent data
ResetTemplateCache=Reset Template Cache
TabServer=Server
TabLog=Log
Sent=Sent:
ActiveSessions=Active Sessions:
RequestCount=Request count:
SpeedSimulation=Speed Simulation:
RuntimeParameters=Runtime parameters:
CustomSpeed=Custom speed (kbps)
SpeedNone=None
SpeedCustom=Custom...
AboutIntraWeb=About IntraWeb
IntraWebStandAloneServer=IntraWeb Stand Alone Server
Bytes= bytes
SentData=Reset Sent Data
DefaultBrowserHint=Default Browser
MenuSaveSettingsHint=Save current settings to a .iwb file